export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForDarkBackground: "#D8ECFE",
  colorForNegativeBackground: "#F8DDD7",
  colorRadius: "#C4E2FF",
  colorForNewIcon: "#88AA4D",
  colorForSoftIcon: "#F75531",
  colorForButton: "#FC9B27",
  colorForButtonHover: "#FC7427",
  pagePadding: "90px",
  pagePaddingTopBottom: "180px",
  indent: "20px",
  marginIndent: "64px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px",
  lineHeight: "27px",
};
